### PR TITLE
fix indentLine to operate in absolute values

### PR DESCRIPTION
**Pull request by MateuszZarkowski**
Cleans up indentLine.
This complies with multiple brackets on the same line, that was not possible earlier.
Fixes issues I posted and more.

### CODE REVIEW

**Comment by MateuszZarkowski** [comment]
Damn.
Wait a while with updating.
While this works with UDL languages, I just had it fail with HTML due to the lack of upper 16 bits.

**Comment by ffes** [comment]
First of all, sorry for the delayed reaction.

In your second comment you asked to wait a while. A while has past so thought I asked about it ;-)

Any news on this PR?

And I am working on the 64-bit version of the plugin. Any idea if the bit shifting you use works the same in the 64-bit version of N++?

**Comment by ffes** [comment]
Any news on this PR? Otherwise I'll close it.

**Comment by ffes** [comment]
Closing as announced in https://github.com/ffes/indentbyfold/pull/4#issuecomment-475150516

**Pull request closed without merging**
