### PR TITLE
x64 build on travis

### PR DESCRIPTION
**Pull request by chcg**
- added x64 build on travis mingw
- used new trusty environment, see https://docs.travis-ci.com/user/trusty-ci-environment/
- start of preparation for github deployment, see https://docs.travis-ci.com/user/deployment/releases/

with build time differences:
trusty:
https://travis-ci.org/ffes/indentbyfold/builds/248521746
precise:
https://travis-ci.org/ffes/indentbyfold/builds/248519243

### CODE REVIEW

**Comment by ffes** [comment]
In general it looks good, but when I try to build x64 with with this Makefile I get this error:

```
$ make BITS=64
x86_64-w64-mingw32-g++ -c -O2 -DUNICODE -mtune=i686 -MMD -MP -W -Wall -gstabs -mwindows -o IBFMenu.o IBFMenu.cpp
IBFMenu.cpp:1:0: error: CPU you selected does not support x86-64 instruction set
 #include <windows.h>
 ^
make: *** [Makefile:34: IBFMenu.o] Error 1
```

The `-mtune=i686` is the problem. Will look at the exact reason for option later, but first thought is that it probably can go.

And when that option is removed, you will get this error:

```
make: x86_64-w64-mingw32-windres: Command not found
```

**Comment by ffes** [comment]
And I wonder why you add a `$(OUTDIR)` to `Makefile` and not use it?

**Comment by ffes** [comment]
FYI, I tested with both MSYS2 and Cygwin.

Not sure why there is no `x86_64-w64-mingw32-windres` in both of them but there is one on Linux. And why Linux doesn't seem to mind the `-mi686` flag.

**Comment by ffes** [comment]
Huh, strange things happened on my pc. There is a `x86_64-w64-mingw32-windres.exe` in my Cygwin installation. And now suddenly it can be found by make as well.

**Comment by chcg** [comment]
@ffes Used nppftp config as inspiration and therefore the $(OUTDIR), which is used to build x86 and x64 versions in different dirs which is helpful for local builds x86 in parallel to x64

**Comment by chcg** [comment]
@ffes Any further input needed from my side? Is the build working for you locally?

**Comment by chcg** [comment]
@ffes Rebased to current trunk. Removed unused $(OUTDIR). Is it now ok to be merged?

**Comment by chcg** [comment]
@ffes 
updated with:
-used newer xenial environment, see https://docs.travis-ci.com/user/reference/xenial/

**Pull request merged**
